#[Introduction to Python for Science and Engineering](https://www.taylorfrancis.com/books/mono/10.1201/9780429506413/introduction-python-science-engineering-david-pine)

###The following exercises correspond to chapter [3: Strings, Lists, Arrays, and Dictionaries](https://www.taylorfrancis.com/chapters/mono/10.1201/9780429506413-3/strings-lists-arrays-dictionaries-david-pine)

[old manual (no library access required)](https://physics.nyu.edu/pine/pymanual/html/pymanMaster.html)
[old link (no library access required)](https://physics.nyu.edu/pine/pymanual/html/chap3/chap3_arrays.html)

In [17]:
##RUN THIS CODE BLOCK FIRST - it brings in functions like sin, cos, log, ...
#in the future, we'll do things slightly differently to make your code more robust and portable...
from numpy import *

##3.6.1

Create an array of 9 evenly spaced numbers going from 0 to 29 (inclusive) and give it a variable name $r$. Find the square of each element of the array (as simply as possible). Find twice the value of each element of the array in two different ways: ($i$) using addition and ($ii$) using multiplication. Use the print command to display the results.

In [2]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 3.6.1##
array = [2,4,8,12,16,20,24,28,29]
array2 = []
array2x = []
for x in array:
  y = x+x
  array2.append(y)
print(array2)

for x in array:
  y = 2*x
  array2x.append(y)
print(array2x)



[4, 8, 16, 24, 32, 40, 48, 56, 58]
[4, 8, 16, 24, 32, 40, 48, 56, 58]


##3.6.2

Create the following arrays:
1. an array of 100 elements all equal to $e$, the base of the natural logarithm;
1. an array in 1-degree increments of all the angles in degrees from 0 to 360 degrees;
1. an array in 1-degree increments of all the angles in radians from 0 to 360 degrees;
1. an array from 12 to 17, not including 17, in 0.2 increments;
1. an array from 12 to 17, including 17, in 0.2 increments.

In [66]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 3.6.2#
import numpy as np
e = np.exp(1)
e_array = []
for i in range (100):
  e_array.append(e)
print(e_array)

degrees = []
for i in range(1,361):
  degrees.append(i)
print(degrees)

radians = []
for i in range(1,361):
  radians.append((i*2*pi)/360)
print(radians)

d = 0.2
i = 12
list4 = []
while i < 17:
  list4.append(round(i,2))
  i += d
for x in list4:
  if x == 17:
    list4.remove(x)
print(list4)

list5 = []
z = 12
while z <= 17:
  list5.append(round(z,2))
  z += 0.2
print(list5)



[2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828459045, 2.718281828

##3.6.3

The position of a ball at time $t$ dropped with zero initial velocity from a height $h_0$ is given by

$y = h_0 - \frac{1}{2} gt^2$

where $g=9.8$ m/s$^2$. Suppose $h_0 = 10$ m. Find the sequence of times when the ball passes each half meter assuming the ball is dropped at $t=0$. Hint: Create a NumPy array for $y$ that goes from 10 to 0 in increments of -0.5 using the `arange` fucntion. Solving the above equation for $t$, we find that

$t = \sqrt{\frac{2\left(h_0 -y\right)}{g}}$

Using this equation and the array you created, find the sequence of times when the ball passes each half meter. Your code should yield the following results for the $y$ and $t$ arrays:

```
In [2]: y
Out[2]: array([10. , 9.5, 9. , 8.5, 8. , 7.5, 7. , 6.5,
                6. , 5.5, 5. , 4.5, 4. , 3.5, 3. , 2.5,
                2. , 1.5, 1. , 0.5])

In [3]: t
Out[3]: array([ 0.        , 0.31943828, 0.45175395,
                0.55328334, 0.63887656, 0.71428571,
                0.7824608 , 0.84515425, 0.9035079 ,
                0.95831485, 1.01015254, 1.05945693,
                1.10656667, 1.15175111, 1.19522861,
                1.23717915, 1.27775313, 1.31707778,
                1.35526185, 1.39239919])
```


In [73]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 3.6.3##
h0 = 10

g = 9.8

def getT(y):
  t = sqrt((2*(h0-y))/g)
  return t

y = np.arange(10,0,-0.5)
y = list(y)
print(y)

z = []
for x in y:
  z.append(getT(x))
print(z)


[10.0, 9.5, 9.0, 8.5, 8.0, 7.5, 7.0, 6.5, 6.0, 5.5, 5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5]
[0.0, 0.3194382824999699, 0.4517539514526256, 0.5532833351724881, 0.6388765649999398, 0.7142857142857143, 0.7824607964359516, 0.8451542547285166, 0.9035079029052512, 0.9583148474999098, 1.0101525445522108, 1.0594569267279519, 1.1065666703449761, 1.1517511068997928, 1.1952286093343936, 1.2371791482634837, 1.2777531299998797, 1.3170777796132696, 1.3552618543578767, 1.3923991921155663]


##3.6.4

Recalling that the average velocity over an interval $\Delta t$ is defined as $\bar{v}=\Delta y/ \Delta t$, find the average velocity for each time interval in the previous problem using NumPy arrays. Keep in mind that the number of time intervals is one less than the number of times. Hint: What are the arrays `y[1:20]` and `y[0:19]`? What does the array `y[1:20]-y[0:19]` represent? (Try printing out the two arrays from the IPython shell.) Using this last array and a similar one involving time, find the array of average velocities. Bonus: Can you think of a more elegant way of representing `y[1:20]-y[0:19]` that does not make explicit reference to the number of elements in the `y` array--one that would work for any length array?

You should get the following answer for the array of velocities:

```
In [5]: v
Out[5]: array([-1.56524758,  -3.77884195,  -4.9246827 ,
               -5.84158351,  -6.63049517,  -7.3340579 ,
               -7.97531375,  -8.56844457,  -9.12293148,
               -9.64549022,  -10.14108641, -10.61351563,
               -11.06575711, -11.50020061, -11.91879801,
               -12.32316816, -12.71467146, -13.09446421,
               -13.46353913])
```


In [83]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 3.6.4##
y = array(y)
z = array(z)
m = (y[1:20]-y[0:19])/(z[1:20]-z[0:19])
print(list(m))

#bonus:
velocities = []
for i in range(1,len(z)):
  v = (y[i]-y[i-1])/(z[i]-z[i-1])
  velocities.append(v)
print(velocities)

[-1.565247584249853, -3.778841946367718, -4.924682704463059, -5.841583510844899, -6.6304951684996976, -7.334057902536167, -7.975313750705891, -8.56844457240547, -9.122931476985292, -9.645490221055367, -10.141086409272804, -10.613515625657383, -11.06575710849935, -11.500200609547521, -11.91879801222959, -12.323168163490518, -12.714671457104401, -13.094464206458643, -13.463539127719816]
[-1.565247584249853, -3.778841946367718, -4.924682704463059, -5.841583510844899, -6.6304951684996976, -7.334057902536167, -7.975313750705891, -8.56844457240547, -9.122931476985292, -9.645490221055367, -10.141086409272804, -10.613515625657383, -11.06575710849935, -11.500200609547521, -11.91879801222959, -12.323168163490518, -12.714671457104401, -13.094464206458643, -13.463539127719816]
